### PR TITLE
Several improvements for working with millions of jobs

### PR DESCRIPTION
**Pull request by kjoe**
Wouldn't be practical to maintain a dev branch? :)

### CODE REVIEW

**Comment by tkang007** [comment]
Could you please merge this updating?

Is there any way to include EC2 no public ipv4 case ?

**Comment by SergeyTsalkov** [comment]
I'm reviewing this now, but it's a very large pull request. Some of it I'm quite happy with, others I'm still trying to fully understand. Are you available to chat?

**Comment by SergeyTsalkov** [comment]
This pull request includes many different features. That makes it hard to review, and I can't merge it until I'm happy with all of the things in it. In the future, please submit one pull request per feature. Here are my reactions to the parts of this one.

GOOD - I'm willing to merge these if you make a separate pull request with all of them.
Reduce key scan CPU load impact on redis server with very high number
Adding basepath to web configuration
Removing executable flag from .go files
Adding keyboard navigation
Hide DeleteAll and RetryAll buttons on empty job lists
Delete some obsolete code
Getting current time from redis server for scheduling cron jobs



COCERNS
Adding new environment variables to support custom deployments
Adding resource handler to avoid external requests, and distribute lo
  * What's wrong with serving the JS from CDNs? Why do you need to keep local copies?

Drastic speeding up searching in job lists with huge number of jobs
  * globally shared hitsJson results in possible race conditions
  * globally shared hitsJson means that running different searches in separate browser tabs will produce wrong results

Spreading job logs across Redis Cluster server nodes
  * I thought redis cluster hashes the entire key for sharding data. Why do you need to start the log names with a different word?

New options to set different expire time to failed job logs, and set
  * This is an important feature, but I'd prefer to make some changes to it myself. I'll make my own commit based on your code.

**Comment by kjoe** [comment]
Thank you for the reviews! You're right, I've split things to several pull requests, rather than my whole/increased dev branch, sorry.

I've completely remove that ugly resourcehandler feature, it's not a big issue, just was an experiment, when using brooce without external network.

I've corrected search concurrency problem mentioned above.

Using Brooce on Redis Cluster only works, when all keys hashes to the same hash slot (because of multi-key operations), so you can only employs one redis master node, with key hash tagging (eg. "{Brooce}"). It's OK in most cases, because there are low number of lists, but when you've verly large number of job logs, then worth to spreading logs to all redis nodes (logs are independent, expires, and not part of any multi-key oprerations).

The log spreading and done/failed list expiring features are memory-saving improvements for redis, feel free to modify in favour of your own preferences.

Thanks!

**Pull request closed without merging**
